# Generated by Django 5.1.1 on 2024-09-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0002_carbrandsubtitle_carbrandtitle_carfueltype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carbrandsubtitle",
            old_name="brandTitle",
            new_name="brand_title",
        ),
    ]
