# Generated by Django 5.1.1 on 2024-09-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0003_rename_brandtitle_carbrandsubtitle_brand_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carbrandmodel",
            old_name="brandSubtitle",
            new_name="brand_subtitle",
        ),
    ]
