# Generated by Django 5.1.1 on 2024-09-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0004_rename_brandsubtitle_carbrandmodel_brand_subtitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(max_length=50)),
            ],
        ),
    ]
