# Generated by Django 5.1.1 on 2024-09-21 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0005_statelist"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carBrand", models.CharField(max_length=50)),
                ("carModel", models.CharField(max_length=50)),
                ("carYear", models.PositiveIntegerField()),
                ("carFuel", models.CharField(max_length=50)),
                ("carTransmission", models.CharField(max_length=50)),
                ("carKM", models.CharField(max_length=50)),
                ("carOwners", models.CharField(max_length=50)),
                ("carTitle", models.CharField(max_length=50)),
                ("carDescription", models.TextField()),
                ("carPrice", models.PositiveIntegerField()),
                ("carState", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_image", models.ImageField(upload_to="car_images/")),
                (
                    "car_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_images",
                        to="olxapi.cardata",
                    ),
                ),
            ],
        ),
    ]
