# Generated by Django 5.1.1 on 2024-09-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0007_cardata_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="CarImage", new_name="CarCompleteData",),
        migrations.RenameField(
            model_name="carcompletedata", old_name="car_image", new_name="carPhotos",
        ),
    ]
