# Generated by Django 5.1 on 2024-09-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0008_rename_carimage_carcompletedata_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carcompletedata", old_name="carPhotos", new_name="image",
        ),
    ]
