# Generated by Django 5.1.1 on 2024-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0009_rename_carphotos_carcompletedata_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardata",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cardata",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
