# Generated by Django 5.1.1 on 2024-09-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0010_cardata_email_cardata_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="cardata", name="user",),
    ]
