# Generated by Django 5.1.1 on 2024-10-02 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0013_petdata_petcompletedata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobSalaryPeriod", models.CharField(max_length=50)),
                ("jobPositionType", models.CharField(max_length=50)),
                ("jobSalaryFrom", models.PositiveIntegerField()),
                ("jobSalaryTo", models.PositiveIntegerField()),
                ("jobTitle", models.CharField(max_length=50)),
                ("jobDescription", models.TextField()),
                ("jobPrice", models.PositiveIntegerField()),
                ("jobState", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobCompleteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="job_images/")),
                (
                    "job_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_images",
                        to="olxapi.jobdata",
                    ),
                ),
            ],
        ),
    ]
