# Generated by Django 5.1.1 on 2024-10-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0014_jobdata_jobcompletedata"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobdata", name="jobPrice",),
    ]
