# Generated by Django 5.1.1 on 2024-10-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0015_remove_jobdata_jobprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdata",
            name="jobState",
            field=models.CharField(max_length=255),
        ),
    ]
