# Generated by Django 5.1.1 on 2024-10-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0016_alter_jobdata_jobstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdata",
            name="jobState",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="jobdata",
            name="jobTitle",
            field=models.CharField(max_length=255),
        ),
    ]
