# Generated by Django 5.1.1 on 2024-10-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0019_fashiondata_fashioncompletedata_furnituredata_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="uFrnitureCompleteData", new_name="FrnitureCompleteData",
        ),
    ]
