# Generated by Django 5.1.1 on 2024-10-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0020_rename_ufrniturecompletedata_frniturecompletedata"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FrnitureCompleteData", new_name="FurnitureCompleteData",
        ),
    ]
