# Generated by Django 5.1.1 on 2024-10-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0021_rename_frniturecompletedata_furniturecompletedata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fashiondata",
            name="fashionTitle",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="furnituredata",
            name="furnitureTitle",
            field=models.CharField(max_length=255),
        ),
    ]
