# Generated by Django 5.1.1 on 2024-10-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0023_bookssportshobbiesdata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookssportshobbiesdata",
            name="booksSportsHobbiesTitle",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="cardata",
            name="carTitle",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="electronicappliancedata",
            name="electronicApplianceTitle",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="fashiondata",
            name="fashionTitle",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="furnituredata",
            name="furnitureTitle",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="petdata",
            name="petTitle",
            field=models.CharField(max_length=150),
        ),
    ]
