# Generated by Django 5.1.1 on 2024-10-07 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "olxapi",
            "0024_alter_bookssportshobbiesdata_bookssportshobbiestitle_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileBrandTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MobileBrandSubtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "brand_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brandsubtitle",
                        to="olxapi.mobilebrandtitle",
                    ),
                ),
            ],
        ),
    ]
