# Generated by Django 5.1.1 on 2024-10-07 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0025_mobilebrandtitle_mobilebrandsubtitle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobileSubcategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mobileBrand", models.CharField(blank=True, max_length=50, null=True)),
                ("mobileTitle", models.CharField(max_length=50)),
                ("mobileDescription", models.TextField()),
                ("mobilePrice", models.PositiveIntegerField()),
                ("mobileState", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MobileCompleteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="mobile_images/")),
                (
                    "mobile_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_images",
                        to="olxapi.mobiledata",
                    ),
                ),
            ],
        ),
    ]
