# Generated by Django 5.1.1 on 2024-10-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0026_mobiledata_mobilecompletedata"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobiledata",
            name="mobileType",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
