# Generated by Django 5.1.1 on 2024-10-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0027_mobiledata_mobiletype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobiledata",
            old_name="mobileSubcategory",
            new_name="subcategory",
        ),
    ]
