# Generated by Django 5.1.1 on 2024-10-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0029_cvsdata_cvscompletedata"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvsdata",
            name="cvsKMDriven",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cvsdata",
            name="cvsYear",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
