# Generated by Django 5.1.1 on 2024-10-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0030_cvsdata_cvskmdriven_cvsdata_cvsyear"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cvsdata", old_name="cvsSubcategory", new_name="subcategory",
        ),
    ]
