# Generated by Django 5.1.1 on 2024-10-10 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0031_rename_cvssubcategory_cvsdata_subcategory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "educationClassesType",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tourstravelType",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "electronicsrepairservicesType",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "healthbeautyType",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "homerenovationrepairType",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cleaningpestcontrolType",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "legaldocumentationType",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "packersmoversType",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "otherservicesType",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("serviceTitle", models.CharField(max_length=50)),
                ("serviceDescription", models.TextField()),
                ("servicePrice", models.PositiveIntegerField()),
                ("serviceState", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCompleteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="service_images/")),
                (
                    "service_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_images",
                        to="olxapi.servicedata",
                    ),
                ),
            ],
        ),
    ]
