# Generated by Django 5.1.1 on 2024-10-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0032_servicedata_servicecompletedata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicedata",
            old_name="educationClassesType",
            new_name="educationclassesType",
        ),
    ]
