# Generated by Django 5.1.1 on 2024-10-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0033_rename_educationclassestype_servicedata_educationclassestype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedata",
            name="serviceTitle",
            field=models.CharField(max_length=100),
        ),
    ]
