# Generated by Django 5.1.1 on 2024-10-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0034_alter_servicedata_servicetitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedata",
            name="serviceTitle",
            field=models.CharField(max_length=255),
        ),
    ]
