# Generated by Django 5.1.1 on 2024-10-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0035_alter_servicedata_servicetitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectronicRepairType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("er_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HomeRenovationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hr_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ToursType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tours_name", models.CharField(max_length=100)),
            ],
        ),
    ]
