# Generated by Django 5.1.1 on 2024-10-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0036_electronicrepairtype_homerenovationtype_tourstype"),
    ]

    operations = [
        migrations.RemoveField(model_name="servicedata", name="servicePrice",),
    ]
