# Generated by Django 5.1.1 on 2024-10-14 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0038_bicyclebrandtitle_motorcyclebrandtitle_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BikeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bikeBrand", models.CharField(max_length=50)),
                ("bikeModel", models.CharField(max_length=50)),
                ("bikeYear", models.PositiveIntegerField()),
                ("bikeKM", models.CharField(max_length=50)),
                ("bikeTitle", models.CharField(max_length=50)),
                ("bikeDescription", models.TextField()),
                ("bikePrice", models.PositiveIntegerField()),
                ("bikeState", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BikeCompleteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="bike_images/")),
                (
                    "bike_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bike_images",
                        to="olxapi.bikedata",
                    ),
                ),
            ],
        ),
    ]
