# Generated by Django 5.1.1 on 2024-10-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0039_bikedata_bikecompletedata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="motorcyclebrandmodel",
            old_name="brand_subtitle",
            new_name="brand_title",
        ),
        migrations.RenameField(
            model_name="scooterbrandmodel",
            old_name="brand_subtitle",
            new_name="brand_title",
        ),
    ]
