# Generated by Django 5.1.1 on 2024-10-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "olxapi",
            "0040_rename_brand_subtitle_motorcyclebrandmodel_brand_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikedata",
            name="bikeBrand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bikedata",
            name="bikeKM",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bikedata",
            name="bikeModel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bikedata",
            name="bikeYear",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
