# Generated by Django 5.1.1 on 2024-10-17 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0041_alter_bikedata_bikebrand_alter_bikedata_bikekm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "propertyType",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("propertyBHK", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "propertyBathrooms",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyFurnishing",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyListedBy",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertySuperBuiltUpArea",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyCarpetArea",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyMaintenance",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyTotalFloors",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyFloorNo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyBachelorsAllowed",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyCarParking",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyFacing",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyPlotArea",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyLength",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyBreadth",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyWashrooms",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyProjectStatus",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertySubtype",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyMealsIncluded",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "propertyProjectName",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("propertyTitle", models.CharField(max_length=50)),
                ("propertyDescription", models.TextField()),
                ("propertyPrice", models.PositiveIntegerField()),
                ("propertyState", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyCompleteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images/")),
                (
                    "property_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_images",
                        to="olxapi.propertydata",
                    ),
                ),
            ],
        ),
    ]
