# Generated by Django 5.1.1 on 2024-10-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0042_propertydata_propertycompletedata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydata",
            name="propertyTitle",
            field=models.CharField(max_length=255),
        ),
    ]
