# Generated by Django 5.1.1 on 2024-11-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0044_bikedata_category_bookssportshobbiesdata_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvsdata",
            name="cvsTitle",
            field=models.CharField(max_length=255),
        ),
    ]
