# Generated by Django 5.1.1 on 2024-12-18 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olxapi", "0046_chatroom_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="content", new_name="text",
        ),
        migrations.RemoveField(model_name="chatroom", name="buyer",),
        migrations.RemoveField(model_name="chatroom", name="created_at",),
        migrations.RemoveField(model_name="chatroom", name="seller",),
        migrations.AddField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(
                related_name="chatrooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
